/*
 * File: app/model/tree_model_objects.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Termo.model.tree_model_objects', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'text'
        },
        {
            name: 'HumidMax'
        },
        {
            name: 'HumidMin'
        },
        {
            name: 'TermoMax'
        },
        {
            name: 'TermoMin'
        },
        {
            name: 'unit_id'
        },
        {
            name: 'icon',
            type: 'string'
        },
        {
            name: 'leaf',
            type: 'boolean'
        },
        {
            name: 'expanded',
            type: 'boolean'
        },
        {
            name: 'children'
        }
    ]
});