/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({

    requires: [
        'Ext.util.Point',
        'Termo.Utilities'
    ],
    models: [
        'model_temperature',
        'tree_model_objects',
        'model_humid'
    ],
    stores: [
        'store_temperature',
        'tree_store_objects',
        'store_humid'
    ],
    views: [
        'MyViewport',
        'MyLabel'
    ],
    controllers: [
        'MainView_Controller'
    ],
    name: 'Termo',

    launch: function() {
        Date.prototype.toLocaleFormat = function(format) {


            this.setTime (((this.getTime()/1000.0) - (this.getTimezoneOffset()*60)) * 1000);



            var f = {y : this.getYear() + 1900,m : this.getMonth() + 1,d : this.getDate(),H : this.getHours(),M : this.getMinutes(),S : this.getSeconds()};
            for(var k in f)
                format = format.replace('%' + k, f[k] < 10 ? "0" + f[k] : f[k]);
            return format;
        };


        Date.prototype.toLocaleFormat2 = function(format) {


        //    this.setTime (((this.getTime()/1000.0) - (this.getTimezoneOffset()*60)) * 1000);



            var f = {y : this.getYear() + 1900,m : this.getMonth() + 1,d : this.getDate(),H : this.getHours(),M : this.getMinutes(),S : this.getSeconds()};
            for(var k in f)
                format = format.replace('%' + k, f[k] < 10 ? "0" + f[k] : f[k]);
            return format;
        };

        var getParams = document.URL.split("?");
        var params = Ext.urlDecode(getParams[getParams.length - 1]);






        if (!params.access_token)
        {
            new Termo.view.MyViewport({
            title : "iframe",
            width : 300,
            height: 300,
            layout : 'fit',
            items : [{
                xtype : "component",
                autoEl : {
                    tag : "iframe",
                    src : "http://hosting.wialon.com/login.html?redirect_uri=" + GlobalVars.url_setting + "&duration=86400"
                    //src : "http://hosting.wialon.com/login.html?redirect_uri=http://localhost/xxx/&duration=86400"
                }
                }]
            }).show();

        //    Ext.MessageBox.alert('Ошибка авторизации', 'Вы не авторизованы');
        //    var main_window = Ext.getCmp('id_main_view');
        //    main_window.setDisabled(true);

        }
        else
        {
            new Termo.view.MainView().show();



            Ext.data.JsonP.request(
        		{
        			url: GlobalVars.url_setting + 'php/login.php',
        			params:
        			{
                        token: params.access_token,
        				format: 'json'
        			},
        			callbackKey: 'callback',
        			async: false,
        			success: function (result)
        			{
                        console.log (result);



        				if (result.error == 8)
                            Ext.MessageBox.alert('Ошибка Wialon', 'Неверный токен');
        				else if (result.error == 4)
                            Ext.MessageBox.alert('Ошибка Wialon', 'Ошибка ввода Wialon');
        				else if (result.eid.length !== 0)
                        {
                            GlobalVars.eid = result.eid;

                            Termo.Utilities.set_user_lbl (result.au);

                            Termo.Utilities.get_unit_group_list();
                            Termo.Utilities.get_unit_list();
                            Termo.Utilities.get_report_template_data();
                            Termo.Utilities.start_tasks ();


                        }
                        else
                           Ext.MessageBox.alert('Ошибка Wialon', result.error);

        			}
        		});


            GlobalVars.current_period_type = 1;
        }






    }

});
